### ISSUE TITLE
add group links to top menu and footer

### ISSUE THREAD

**Issue by cmsirbu** [cmsirbu/inog#16]
See title, pending footer text from @donalod

**Comment by donalod** [comment]
```<p>We also announce on a <a href="https://groups.google.com/d/forum/inog" target="_blank" class="text-success"><strong>Google Group</a></strong> which you can <a href="https://groups.google.com/d/forum/inog" target="_blank" class="text-success"><strong>join here.</a></strong> however our main tools a <strong><a href="http://www.meetup.com/Irish-Network-Operators-Group/" target="_blank" class="text-success">Meetup Group</a></strong> and Slack. <a href="https://slack.inog.net"></a></p>```
